version: 3
tasks:
  install-dependencies:
    desc: Install library dependencies.
    sources:
      - pyproject.toml
    cmd: uv sync

  unit-tests:
    desc: Run unit tests on code.
    dir: test
    deps:
      - install-dependencies
    cmds:
      - PYTHONPATH=../ uv run test_main.py
